package day8

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestPart1(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`
	solution, err := Part1(input)
	require.Nil(t, err)
	require.Equal(t, "14", solution)
}

func TestPart2(t *testing.T) {
	input := `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`
	solution, err := Part2(input)
	require.Nil(t, err)
	require.Equal(t, "34", solution)
}
